name: policies/docker-pr

on:
  workflow_dispatch:
  pull_request:

jobs:
  docker-lint:
    uses: forvia-poc/actions/.github/workflows/docker-lint.yml@features/workflow-docker-lint
  
  docker-build:
    uses: forvia-poc/actions/.github/workflows/docker-build.yml@features/workflow-docker-build
