name: policies/docker-pr

on:
  workflow_dispatch:
  pull_request:

jobs:
  docker-lint:
    uses: forvia-poc/actions/.github/workflows/docker-lint.yml@main
  
  docker-build:
    uses: forvia-poc/actions/.github/workflows/docker-build.yml@main
