name: build/docker-ci

on:
  workflow_dispatch:
  push:
    branches:
      - $default-branch

jobs:
  docker-build-push:
    uses: forvia-poc/actions/.github/workflows/docker-build-push.yml@main
    with:
      image_repository: ${{ vars.IMAGE_REPOSITORY }}
      image_tag: latest
      registry_server: ${{ vars.REGISTRY_SERVER }}
      registry_username: ${{ vars.REGISTRY_USERNAME }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
